# Generated by Django 5.2.13 on 2026-04-28 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_callroom_callsignal'),
    ]

    operations = [
        migrations.AddField(
            model_name='callroom',
            name='answer_sdp',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='callroom',
            name='offer_sdp',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
