# Generated by Django 4.2.30 on 2026-04-30 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_conversation_chatmessage'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['last_message_time'], name='accounts_co_last_me_e214d2_idx'),
        ),
    ]
