# Generated by Django 4.2.30 on 2026-05-04 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_messagereaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='replied_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='accounts.chatmessage'),
        ),
    ]
