# Generated by Django 4.2.30 on 2026-05-04 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_chatmessage_replied_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='is_forwarded',
            field=models.BooleanField(default=False),
        ),
    ]
