# Generated by Django 4.2.30 on 2026-05-07 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_gameinvitation_chessgame'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameinvitation',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitation', to='accounts.chessgame'),
        ),
    ]
