# Generated by Django 4.2.30 on 2026-05-10 06:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_gameinvitation_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callroom',
            name='room_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
