# Generated by Django 4.2.30 on 2026-06-01 07:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0015_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordedCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('recording_file', models.FileField(blank=True, null=True, upload_to='call_recordings/')),
                ('call_type', models.CharField(default='unknown', max_length=50)),
                ('callee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_calls_received', to=settings.AUTH_USER_MODEL)),
                ('caller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_calls_made', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
