# Generated by Django 4.2.30 on 2026-06-11 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_notificationlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='allow_calls',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='allow_invitations',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='allow_messages',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='allow_sticky',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('opened', 'Opened'), ('dismissed', 'Dismissed'), ('blocked', 'Blocked')], default='sent', max_length=15),
        ),
    ]
