# Generated by Django 4.2.30 on 2026-06-11 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_userprofile_allow_calls_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationlog',
            name='status',
            field=models.CharField(choices=[('failed', 'Failed'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('opened', 'Opened'), ('dismissed', 'Dismissed'), ('blocked', 'Blocked')], default='failed', max_length=15),
        ),
    ]
