# Generated by Django 4.2.30 on 2026-07-03 08:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0021_otp_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationlog',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='accepted_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
