# Generated by Django 4.2.30 on 2026-05-27 08:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('media', '0002_alter_gamevideo_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserVoiceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_audio', models.FileField(blank=True, null=True, upload_to='voice_refs/')),
                ('is_trained', models.BooleanField(default=False)),
                ('siliconflow_voice_uri', models.CharField(blank=True, max_length=256)),
                ('elevenlabs_voice_id', models.CharField(blank=True, max_length=256)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='voice_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VoiceResponseCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_hash', models.CharField(db_index=True, max_length=64)),
                ('audio_file', models.FileField(upload_to='voice_cache/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'text_hash')},
            },
        ),
    ]
